### PR TITLE
Fixed checkbox read for preview

### LINKED ISSUE #647: Checkbox content type return in preview string with 'false' not boolean

### PR DESCRIPTION
**Pull request by wachterjohannes**
__Tasks:__

- [ ] gather feedback for my changes

__Informations:__

| Q             | A
| ------------- | ---
| Tests pass?   | yes => no changes
| Fixed tickets | fixes #647
| BC Breaks     | none
| Doc           | none

### CODE REVIEW

**Comment by danrot** [comment]
Falsy values do not produce preview update

**Comment by wachterjohannes** [comment]
@danrot fixed

**Comment by danrot** [comment]
After clicking on a checkbox you still have to  click somewhere else for the preview to update, I guess that's because there is no focus out event otherwise. Maybe we should adapt the dom filter for checkboxes?

**Comment by wachterjohannes** [comment]
@danrot i have added a changed event for radio and checkbox

**Pull request merged**
