### PR TITLE
Add sorting support to internal links and snippets

### LINKED ISSUE #423: [ContentBundle] Internal link HOTFIX
<a href="https://github.com/wachterjohannes"></a>
By @wachterjohannes *from* https://github.com/sulu-cmf/SuluContentBundle/issues/224

https://github.com/sulu-cmf/SuluContentBundle/pull/217/files#diff-31d2735a0d4522ccecf3874299440ea3R34

I will observe this issue with real installations and remove it as soon as possible!

### LINKED ISSUE #554: Version 0.10.2 property media_selection
If you assign more than 10 images in a media selection, they will be shown on the page, but if you want to delete or watch the assigned images in the media selection again you can't display more than 10 images.

bildschirmfoto 2014-11-13 um 17 25 27

### LINKED ISSUE #780: Sorting of snippets and internal link selection
For media it is don by @danrot in pr https://github.com/sulu-cmf/sulu/pull/738

### PR DESCRIPTION
**Pull request by danrot**
This PR extracts a lot of functionality from the media content type (especially the sorting) into a new type in Husky, and adapts the internal links and snippets to this new type. Enables the sorting for these content types.

Depends on this Husky PR: https://github.com/massiveart/husky/pull/449

__Tasks:__

- [x] test coverage
- [ ] gather feedback for my changes
- [ ] submit changes to the documentation
- [x] added changelog line
- [x] fix internal links storage (array of references instead of JSON string)
- [x] fix snippet storage (array of references instead of JSON string)
- [x] write migration script for internal link and snippet content type
- [x] check https://github.com/sulu-cmf/sulu/issues/423
- [x] check if preview is still working with sorting
- [x] check automatic load on empty media 
- [x] add internal links without reloading the list
- [x] check if multiple media assignments work in the same templates
- [x] check #554 

__Informations:__

| Q             | A
| ------------- | ---
| Fixed tickets | fixes #780 , fixes #423, fixes #554, fixes https://github.com/sulu-cmf/sulu-standard/issues/254
| BC Breaks     | none
| Doc           | none

### CODE REVIEW

**Comment by danrot** [comment]
I would like to update the way the internal links are stored. Currently the internal links also have a display option, which is actually not available at all. I would prefer a simple array instead, which would also give us some advantages, e.g. correct reference handling in PHPCR. But I am afraid that we would have to update the current installations, maybe an migration script should be added?

/cc @chirimoya

**Comment by chirimoya** [comment]
+1 for storage optimization, but only if a migration scripts will be provided which work fine ;-)

**Comment by danrot** [comment]
Of course it will work fine ;-P

**Comment by danrot** [comment]
@dantleech I have seen that you have been saving the snippets without any additional data as references anyway, so it really doesn't make sense to build this array with the `ids`-key in the code. The harder part to keep BC is the data in the content repository.

And I have got another question: I would have liked to save the internal links the same way, but it looks like the page is broken when you link a page to itself. We would have to prohibit that, but I would like to do that later... Would it be easy to change existing data from an simple array to an array of references?

**Comment by wachterjohannes** [comment]
@danrot ACK when new release of jackalope is ready!

**Pull request merged**
